# Generated by Django 5.2.5 on 2025-09-14 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("duracion_semestres", models.PositiveIntegerField(default=8)),
                ("is_activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="FranjaHoraria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 'Bloque 1', '1era Hora'", max_length=50
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("duracion_minutos", models.PositiveIntegerField(editable=False)),
                ("is_activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Franja Horaria",
                "verbose_name_plural": "Franjas Horarias",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("dia_semana", "hora_inicio", "hora_fin")},
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=15, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("creditos", models.PositiveIntegerField(default=3)),
                ("horas_semanales", models.PositiveIntegerField(default=4)),
                (
                    "semestre",
                    models.PositiveIntegerField(
                        help_text="Semestre en el que se cursa normalmente"
                    ),
                ),
                ("is_activa", models.BooleanField(default=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="planificacion.carrera",
                    ),
                ),
                (
                    "prereq_materias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="materias_dependientes",
                        to="planificacion.materia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia",
                "verbose_name_plural": "Materias",
                "ordering": ["carrera", "semestre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("semestre", "Semestre"),
                            ("cuatrimestre", "Cuatrimestre"),
                            ("trimestre", "Trimestre"),
                            ("anual", "Anual"),
                        ],
                        default="semestre",
                        max_length=15,
                    ),
                ),
                ("anio", models.PositiveIntegerField()),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Número del periodo en el año (1, 2, etc.)"
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("is_activo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Período",
                "verbose_name_plural": "Períodos",
                "ordering": ["-anio", "-numero"],
                "unique_together": {("anio", "numero", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="PlanificacionAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("revision", "En Revisión"),
                            ("aprobada", "Aprobada"),
                            ("vigente", "Vigente"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "carreras",
                    models.ManyToManyField(
                        related_name="planificaciones", to="planificacion.carrera"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planificaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planificaciones",
                        to="planificacion.periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planificación Académica",
                "verbose_name_plural": "Planificaciones Académicas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
