# Generated by Django 5.2.5 on 2025-09-14 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aulas", "0001_initial"),
        ("planificacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignacionDocente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carga_horaria_semanal",
                    models.PositiveIntegerField(help_text="Horas semanales asignadas"),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("is_activa", models.BooleanField(default=True)),
                (
                    "docente",
                    models.ForeignKey(
                        limit_choices_to={"rol": "docente"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_docente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="planificacion.materia",
                    ),
                ),
                (
                    "planificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_docente",
                        to="planificacion.planificacionacademica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Docente",
                "verbose_name_plural": "Asignaciones de Docentes",
                "unique_together": {("docente", "materia", "planificacion")},
            },
        ),
        migrations.CreateModel(
            name="HorarioClase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacidad_estudiantes", models.PositiveIntegerField(default=30)),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("virtual", "Virtual"),
                            ("hibrida", "Híbrida"),
                        ],
                        default="presencial",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("is_activa", models.BooleanField(default=True)),
                (
                    "asignacion_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="asignaciones.asignaciondocente",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clases",
                        to="aulas.aula",
                    ),
                ),
                (
                    "franja_horaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clases",
                        to="planificacion.franjahoraria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Clase",
                "verbose_name_plural": "Horarios de Clases",
                "unique_together": {("franja_horaria", "aula")},
            },
        ),
        migrations.CreateModel(
            name="ConflictoHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("docente_sobrecarga", "Docente con sobrecarga horaria"),
                            ("aula_ocupada", "Aula ocupada en mismo horario"),
                            (
                                "estudiante_conflicto",
                                "Conflicto de horario para estudiantes",
                            ),
                            ("prereq_no_cumplido", "Prerequisito no cumplido"),
                            ("capacidad_excedida", "Capacidad del aula excedida"),
                        ],
                        max_length=25,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("resuelto", models.BooleanField(default=False)),
                ("fecha_deteccion", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "planificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflictos",
                        to="planificacion.planificacionacademica",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "horario_clase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asignaciones.horarioclase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflicto de Horario",
                "verbose_name_plural": "Conflictos de Horario",
                "ordering": ["-fecha_deteccion"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("presente", models.BooleanField(default=False)),
                ("tarde", models.BooleanField(default=False)),
                ("justificada", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"rol": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "horario_clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="asignaciones.horarioclase",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_asistencia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Asistencia",
                "verbose_name_plural": "Registros de Asistencia",
                "unique_together": {("horario_clase", "estudiante", "fecha")},
            },
        ),
    ]
