# Generated by Django 5.2.5 on 2025-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="carrera",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_active_telegram",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="telefono",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cedula",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("docente", "Docente"),
                    ("director", "Director"),
                    ("administrador", "Administrador"),
                ],
                default="estudiante",
                max_length=20,
            ),
        ),
    ]
